// Contenido literal del ANEXO I: MANUAL DE HERRAMIENTAS SOSTENIBLES
// "Estrategias proyectuales para la eficiencia energética en viviendas unifamiliares:
//  bases para un manual abierto de buenas prácticas. Caso: San Carlos Centro."
// Tesis de graduación FADU|UNL — Dona Luciano | Ramira Camila

const CATEGORIES = {
  EN: { num: '01', name: 'ENTORNO', tag: '[EN]', type: 'pasiva', color: '#7ca23c' },
  T:  { num: '02', name: 'TIPOLOGÍAS', tag: '[T]', type: 'pasiva', color: '#c3b143' },
  EV: { num: '03', name: 'ENVOLVENTES', tag: '[EV]', type: 'pasiva', color: '#55b8e4' },
  P:  { num: '04', name: 'SISTEMAS DE CONTROL Y PROTECCIÓN', tag: '[P]', type: 'activa', color: '#e56f2c' },
  SC: { num: '05', name: 'SISTEMAS COMPLEMENTARIOS', tag: '[SC]', type: 'activa', color: '#b28c9e' },
  AE: { num: '06', name: 'ARTEFACTOS EFICIENTES', tag: '[AE]', type: 'activa', color: '#5fbd8b' },
  ER: { num: '07', name: 'ENERGÍAS RENOVABLES', tag: '[ER]', type: 'activa', color: '#ef615e' },
  RH: { num: '08', name: 'GESTIÓN DEL RECURSO HÍDRICO', tag: '[RH]', type: 'activa', color: '#2d4a63' },
};

const STRATEGIES = [
  // ============ 01 | ENTORNO [EN] ============
  { code: 'EN01', cat: 'EN', group: 'Emplazamiento e implantación', title: 'RELACIÓN CON LINDEROS',
    text: 'Considerar escala, preexistencias y el impacto de posibles construcciones vecinas sobre el asoleamiento, ventilación.' },
  { code: 'EN02', cat: 'EN', group: 'Emplazamiento e implantación', title: 'CONSIDERACIÓN DE LAS MEDIDAS DEL LOTE',
    text: 'Evaluar cuáles son los lugares más adecuados para aprovechar ganancias solares según las dimensiones del lote.' },
  { code: 'EN03', cat: 'EN', group: 'Emplazamiento e implantación', title: 'ESPACIOS INTERMEDIOS',
    text: 'Incorporar galerías, patios y semicubiertos como espacios intermedios, reguladores climáticos entre interior y exterior.' },
  { code: 'EN04', cat: 'EN', group: 'Emplazamiento e implantación', title: 'RETIROS URBANOS',
    text: 'Incorporar retiros que amplíen la relación entre vivienda y la calle, favoreciendo una mejor calidad ambiental en el espacio público.' },
  { code: 'EN05', cat: 'EN', group: 'Asoleamiento', title: 'ORIENTACIÓN NORTE',
    text: 'Orientar aventanamientos y superficies al norte permitiendo tener mejor control del asoleamiento en diferentes estaciones.' },
  { code: 'EN06', cat: 'EN', group: 'Asoleamiento', title: 'ORIENTACIÓN ESTE',
    text: 'Orientar las aberturas hacia el este en ambientes de uso diurno, favoreciendo el ingreso de luz natural y el asoleamiento durante las mañanas.' },
  { code: 'EN07', cat: 'EN', group: 'Asoleamiento', title: 'EJE LONGITUDINAL ESTE-OESTE',
    text: 'Disponer siempre que sea posible el volumen sobre su eje mayor este–oeste para obtener ganancias solares pasivas sobre la fachada norte.' },
  { code: 'EN08', cat: 'EN', group: 'Asoleamiento', title: 'CONTROL OESTE',
    text: 'Minimizar superficies expuestas al oeste para disminuir la incidencia de radiación solar y controlar el asoleamiento.' },
  { code: 'EN09', cat: 'EN', group: 'Asoleamiento', title: 'CONTROL SUR',
    text: 'Garantizar una correcta aislación, continuidad de la envolvente, reduciendo las superficies vidriadas en función de los fuertes vientos y la incidencia solar.' },
  { code: 'EN10', cat: 'EN', group: 'Ventilación', title: 'VENTILACIÓN CRUZADA',
    text: 'Disponer aberturas enfrentadas en orientaciones opuestas que favorezcan la circulación continua.' },
  { code: 'EN11', cat: 'EN', group: 'Ventilación', title: 'VENTILACIÓN SELECTIVA',
    text: 'Ubicar aberturas a distintas alturas para favorecer la extracción del aire caliente por convección natural.' },
  { code: 'EN12', cat: 'EN', group: 'Ventilación', title: 'EFECTO CHIMENEA',
    text: 'Incorporar conductos verticales para la extracción del aire caliente mediante diferencia térmica y presión ascendente.' },
  { code: 'EN13', cat: 'EN', group: 'Ventilación', title: 'DEFLECTORES DE VIENTO',
    text: 'Cuando la ventilación cruzada no sea posible, integrar elementos salientes laterales en aberturas para aumentar la velocidad del viento por diferencia de presión.',
    tip: 'Estrategias de ventilación unilateral (EN13) que según la disposición de ventanas y elementos logran incrementar la velocidad interior (Vi) del aire hasta un 35%.' },

  // ============ 02 | TIPOLOGÍAS [T] ============
  { code: 'T01', cat: 'T', group: 'Consideraciones generales', title: 'LOCALES SERVIDOS AL NORTE',
    text: 'Priorizar espacios principales hacia el norte para aprovechar ganancias solares y controles solares.' },
  { code: 'T02', cat: 'T', group: 'Consideraciones generales', title: 'NÚCLEOS AMORTIGUADORES',
    text: 'Utilizar núcleos húmedos, circulaciones y espacios de servicio como franjas de amortiguación hacia el sur y el oeste.' },
  { code: 'T03', cat: 'T', group: 'Consideraciones generales', title: 'SERVICIOS AGRUPADOS',
    text: 'Concentrar núcleos húmedos y técnicos para optimizar instalaciones y reducir recorridos de cañerías.' },
  { code: 'T04', cat: 'T', group: 'Consideraciones generales', title: 'FLEXIBILIDAD DE USOS',
    text: 'Pensar espacios flexibles que admitan distintas configuraciones y cambios de uso según necesidades futuras, sin requerir modificaciones significativas de la estructura.' },
  { code: 'T05', cat: 'T', group: 'Consideraciones generales', title: 'POSIBILIDAD DE CRECIMIENTO',
    text: 'Prever áreas de expansión que permitan futuras ampliaciones de manera ordenada, garantizando la continuidad funcional y constructiva del proyecto.' },
  { code: 'T06', cat: 'T', group: 'Configuraciones tipológicas', title: 'COMPACTA',
    ventajas: ['Alta compacidad.', 'Mínima superficie de envolvente.', 'Menores pérdidas de calor.', 'Menor costo constructivo.', 'Circulaciones mínimas.'],
    desventajas: ['Menor iluminación en zonas centrales.', 'Restricciones en crecimiento (se limita solo a crecimiento vertical).'] },
  { code: 'T07', cat: 'T', group: 'Configuraciones tipológicas', title: 'LINEAL',
    ventajas: ['Óptima cuando el eje longitudinal se dispone en sentido Este-Oeste.', 'Buen aprovechamiento de ganancias solares e iluminación natural.', 'Mejora la relación con el exterior.', 'Optimiza la sectorización y organización de los espacios.'],
    desventajas: ['En lotes con eje norte-sur, procurar que el eje mayor del volumen no se exponga a la orientación oeste, debido a la complejidad del control solar.', 'Mayor superficie de envolvente exterior, aumentando las pérdidas y ganancias de calor.', 'Favorece recorridos longitudinales prolongados, con un consecuente incremento en los costos de construcción.'] },
  { code: 'T08', cat: 'T', group: 'Configuraciones tipológicas', title: 'EN L',
    ventajas: ['Adaptable a diferentes lotes y orientaciones.', 'Favorece la ventilación e iluminación de los espacios.', 'Optimiza la sectorización y organización de los espacios.', 'Capacidad de crecimiento manteniendo lógica del sistema lineal en alas.', 'Favorece la integración con los espacios exteriores.'],
    desventajas: ['Ganancias y pérdidas térmicas medio/alto si no se aprovecha la construcción lindera.', 'Incrementa la superficie de envolvente exterior, aumentando las pérdidas y ganancias térmicas.', 'Requiere una adecuada orientación de cada ala para optimizar el aprovechamiento solar y la ventilación natural.', 'Puede aumentar los recorridos entre espacios.'] },
  { code: 'T09', cat: 'T', group: 'Configuraciones tipológicas', title: 'FRAGMENTADA',
    ventajas: ['Favorece una implantación más adaptable al sitio, integrando los espacios construidos con el entorno.', 'Favorece la ventilación e iluminación de los espacios.', 'Favorece una organización funcional flexible, mediante una clara zonificación de los espacios.', 'Promueve la generación de espacios intermedios que fortalecen la relación entre el interior y el exterior.', 'Promueve configuraciones modulares innovadoras, con alta adaptabilidad y posibilidades de crecimiento.'],
    desventajas: ['Requiere una cuidadosa articulación entre los distintos volúmenes para garantizar una adecuada funcionalidad.', 'Puede aumentar la superficie de circulación y de conexión entre los distintos sectores.', 'Incrementa la complejidad constructiva en las uniones y encuentros entre volúmenes.', 'Puede aumentar la superficie de envolvente expuesta cuando los volúmenes se encuentran muy separados y sin una conexión mediante un espacio central.'] },

  // ============ 03 | ENVOLVENTES [EV] ============
  { code: 'EV01', cat: 'EV', group: 'Muro', title: 'Prefabricado de hormigón',
    capas: ['Pintura látex', 'Panel prefabricado de hormigón hueco', 'Pintura látex'],
    esp: '10cm', k: '4', iram: 'No cumple' },
  { code: 'EV02', cat: 'EV', group: 'Muro', title: 'Ladrillo común (12)',
    capas: ['Pintura látex', 'Revoque interior', 'Ladrillo ceramico macizo', 'Azotado hidrófugo', 'Revoque exterior'],
    esp: '17cm', k: '2,8', iram: 'No cumple' },
  { code: 'EV03', cat: 'EV', group: 'Muro', title: 'Ladrillo hueco (12)',
    capas: ['Revoque fino', 'Revoque grueso', 'Ladrillo cerámico hueco 12cm', 'Azotado hidrófugo', 'Revoque grueso', 'Texturado'],
    esp: '17cm', k: '1,74', iram: 'No cumple' },
  { code: 'EV04', cat: 'EV', group: 'Muro', title: 'Ladrillo hueco (18)',
    capas: ['Revoque fino', 'Revoque grueso', 'Ladrillo cerámico hueco 18 cm', 'Azotado hidrófugo', 'Revoque grueso', 'Texturado'],
    esp: '23cm', k: '1,60', iram: 'No cumple' },
  { code: 'EV05', cat: 'EV', group: 'Muro', title: 'Doble ladrillo común (30)',
    capas: ['Rev. Exterior completo', 'Ladrillo ceramico macizo (27cm)', 'Rev. interior completo'],
    esp: '30cm', k: '1,81', iram: 'No cumple' },
  { code: 'EV06', cat: 'EV', group: 'Muro', title: 'Doble ladrillo común + cámara de aire 3cm',
    capas: ['Ladrillo cerámico macizo', 'Azotado hidrófugo', 'Cámara de aire 3cm', 'Ladrillo cerámico macizo', 'Revoque grueso', 'Revoque fino'],
    esp: '33cm', k: '1,47', iram: 'Tipo C' },
  { code: 'EV07', cat: 'EV', group: 'Muro', title: 'Ladrillo Hueco (18) + EIFS',
    capas: ['Revoque fino', 'Revoque grueso', 'Ladrillo hueco 18 cm', 'Azotado hidrófugo', 'Base coat', 'Placa EPS 25mm', 'Base coat y finish'],
    esp: '25cm', k: '0,8', iram: 'Tipo B' },
  { code: 'EV08', cat: 'EV', group: 'Muro', title: 'Steel Framing',
    capas: ['Placa de yeso', 'Montante PGC 100', 'Lana de vidrio 100mm', 'Placa OSB', 'Barrera de agua y viento', 'Placa EPS 20mm', 'Base coat y finish'],
    esp: '15cm', k: '0,3', iram: 'Tipo A',
    tip: 'Una pared de Steel Framing aisla 9 veces más que una de ladrillo común de similar espesor.' },
  { code: 'EV09', cat: 'EV', group: 'Cubierta', title: 'Losa de hormigón armado (S/Aislación)',
    capas: ['Losa de hormigón armado 0,10 m', 'Film de polietileno', 'Contrapiso', 'Carpeta niveladora impermeable', 'Membrana hidrófuga'],
    esp: '20cm', k: '2,69', iram: 'No cumple' },
  { code: 'EV10', cat: 'EV', group: 'Cubierta', title: 'Chapa (S/Aislación)',
    capas: ['Placa de roca de yeso', 'Cámara de aire (30 cm)', 'Chapa sinusoidal'],
    esp: '31cm', k: '2,43', iram: 'No cumple' },
  { code: 'EV11', cat: 'EV', group: 'Cubierta', title: 'Chapa + 5 Cm lana de vidrio',
    capas: ['Placa de roca de yeso', 'Lana de vidrio 5 cm + barrera de vapor', 'Cámara de aire (30 cm)', 'Chapa sinusoidal'],
    esp: '36cm', k: '0,6', iram: 'Tipo B' },
  { code: 'EV12', cat: 'EV', group: 'Cubierta', title: 'Chapa + (10+5) Cm lana de vidrio',
    capas: ['Placa roca de yeso', 'Lana de vidrio 10 cm + barrera de vapor', 'Placa rigidizadora OSB', 'Barrera de viento y agua Tyvek', 'Lana de vidrio (5 cm)', 'Chapa sinusoidal'],
    esp: '18cm', k: '0,34', iram: 'Tipo B' },
  { code: 'EV13', cat: 'EV', group: 'Cubierta', title: 'Plana Steel Deck + aislación interior',
    capas: ['Placa roca de yeso', 'Lana de vidrio 5 cm + barrera de vapor', 'Chapa encofrado perdido', 'Capa de compresión', 'Contrapiso alivianado perlas EPS (5 cm)', 'Carpeta hidrófuga', 'Piso cerámico'],
    esp: '48cm', k: '0,34', iram: 'Tipo B' },
  { code: 'EV14', cat: 'EV', group: 'Cubierta', title: 'Chapa + 10 Cm lana de vidrio',
    capas: ['Placa de roca de yeso', 'Lana de vidrio 10 cm', 'Cámara de aire (30 cm)', 'Chapa'],
    esp: '41cm', k: '0,34', iram: 'Tipo B' },
  { code: 'EV15', cat: 'EV', group: 'Aventanamientos - consideraciones generales', title: 'CONTROL DE SUPERFICIE VIDRIADA',
    text: 'Regular la proporción entre vidrio y muro según orientación. Se debe disminuir la superficie vidriada evitando pérdidas térmicas.' },
  { code: 'EV16', cat: 'EV', group: 'Aventanamientos - consideraciones generales', title: 'CONTROL DE INFILTRACIONES',
    text: 'Incorporar ruptores de puente térmico (RPT) en carpinterías y burletes para reducir pérdidas energéticas.' },
  { code: 'EV17', cat: 'EV', group: 'Aventanamientos - consideraciones generales', title: 'ABERTURAS OPERABLES',
    text: 'Utilizar aberturas operables que permitan no solo la iluminación, sino también ventilación.' },
  { code: 'EV18', cat: 'EV', group: 'Aventanamientos - consideraciones generales', title: 'CAPAS',
    text: 'Utilizar “capas” (cortinas, vidrio, persianas, postigos) mejoran sustancialmente la eficiencia del aventanamiento tanto en invierno como en verano.' },
  { code: 'EV19', cat: 'EV', group: 'Aventanamientos - vidriado', title: 'VIDRIADO SIMPLE',
    text: 'Evitar colocar vidriado simple en locales de permanencia por la facilidad con que se producen ganancias y pérdidas calóricas.',
    kdato: 'K= 5,8 (W/m²K)' },
  { code: 'EV20', cat: 'EV', group: 'Aventanamientos - vidriado', title: 'DOBLE VIDRIADO HERMÉTICO (DVH) 4+12+4',
    text: 'Incorporar vidrios con cámara de aire hermética para mejorar la aislación térmica y evitar pérdidas del calor interior.',
    kdato: 'K= 2,9 (W/m²K)' },
  { code: 'EV21', cat: 'EV', group: 'Aventanamientos - vidriado', title: 'DOBLE VIDRIADO HERMÉTICO (DVH) LOW-E 4+12+4',
    text: 'Incorporar vidrios con tratamiento de baja emisividad (Low-E) para máxima protección frente a la radiación reflejando el calor y mejorando la aislación.',
    kdato: 'K=1,7 (W/m²K)',
    tip: 'La relación área ventana/muro óptima es de <b>40% de superficie vidriada hacia la orientación norte</b>, mientras que para el resto de las orientaciones es recomendable <b>no superar el 10%</b>.' },
  { code: 'EV22', cat: 'EV', group: 'Aventanamientos - marco', title: 'ALUMINIO SIN RPT',
    text: 'Evitar su uso en espacios habitables por ser un metal altamente conductor y carecer de barreras térmicas, transmitiendo directamente el frío exterior y puede producir condensación.' },
  { code: 'EV23', cat: 'EV', group: 'Aventanamientos - marco', title: 'ALUMINIO RPT',
    text: 'Incorporar RPT en espacios comunes o de presupuesto intermedio, para cortar la transmisión de temperatura, eliminando la condensación superficial y mejorando el confort higrotérmico.' },
  { code: 'EV24', cat: 'EV', group: 'Aventanamientos - marco', title: 'PVC',
    text: 'Incorporar marco de PVC, para el máximo rendimiento térmico y acústico. Priorizar su uso en dormitorios y orientaciones desfavorables.',
    tip: 'La utilización de DVH y persianas exteriores de PVC pueden <b>mejorar un 600%</b> el rendimiento de una ventana con vidriado simple.' },

  // ============ 04 | SISTEMAS DE CONTROL Y PROTECCIÓN [P] ============
  { code: 'P01', cat: 'P', group: 'Horizontal', title: 'ALERO',
    text: 'Incorporar elementos fijos adosados (extensión de cubierta, alero independiente, etc.) opacos que permiten el sombreamiento controlado de la superficie. Recomendables en orientación norte.' },
  { code: 'P02', cat: 'P', group: 'Horizontal', title: 'PÉRGOLA',
    text: 'Disponer elementos horizontales de carácter permeables que permitan el ingreso de luz filtrada que produzcan condiciones de luz variables en los espacios, pudiendo también incorporar vegetación.' },
  { code: 'P03', cat: 'P', group: 'Horizontal', title: 'OPERABLE',
    text: 'Incorporar sistemas regulables (toldos, cubiertas pretensadas o elementos móviles) que permitan adaptarse según estación, clima o uso.' },
  { code: 'P04', cat: 'P', group: 'Vertical', title: 'PARASOL',
    text: 'Incorporar elementos verticales fijos o móviles en fachada para controlar la incidencia solar rasante. Recomendables principalmente en orientación Este-Oeste para reducir la incidencia solar de baja altitud.' },
  { code: 'P05', cat: 'P', group: 'Vertical', title: 'PERSIANAS',
    text: 'Disponer elementos verticales enrollables, para evitar pérdidas térmicas en invierno a través de los aventanamientos.' },
  { code: 'P06', cat: 'P', group: 'Vertical', title: 'CELOSÍA FIJA',
    text: 'Configurar planos permeables (cribado de ladrillos, mallas u otros sistemas) que regulen el ingreso de luz filtrada, viento y visuales según su grado de permeabilidad.' },
  { code: 'P07', cat: 'P', group: 'Vertical', title: 'ESCLUSA',
    text: 'Incorporar dispositivo móvil para permitir transformar la relación espacial entre locales, interior y exterior según condiciones de usos y temperaturas.' },
  { code: 'P08', cat: 'P', group: 'Vertical', title: 'OPERABLE',
    text: 'Incorporar sistemas regulables que permitan ajustar la apertura y el nivel de protección según condiciones de uso y clima.' },
  { code: 'P09', cat: 'P', group: 'Vegetación', title: 'SUELOS VEGETADOS',
    text: 'Sustituir superficies inertes por suelos vegetados para reducir la reflexión térmica, mejorar la infiltración de agua en el terreno y mejorar las condiciones ambientales.' },
  { code: 'P10', cat: 'P', group: 'Vegetación', title: 'VEGETACIÓN CADUCA',
    text: 'Incorporar especies de este tipo para generar sombra en verano e ingreso de radiación solar en invierno.' },
  { code: 'P11', cat: 'P', group: 'Vegetación', title: 'VEGETACIÓN PERENNE',
    text: 'Incorporar especies de follaje permanente para protección solar sobre orientación Oeste, control de visuales y de ventilación.' },
  { code: 'P12', cat: 'P', group: 'Vegetación', title: 'JARDINES VERTICALES',
    text: 'Ubicar capas vegetales sobre las envolventes o protecciones solares para regular la radiación solar, la temperatura, el viento, el ruido y la permeabilidad visual.' },
  { code: 'P13', cat: 'P', group: 'Vegetación', title: 'CUBIERTAS VERDES',
    text: 'Disponer una capa vegetal para reducir la temperatura de la cubierta, retener el agua de lluvia y crear espacios verdes que sirvan como hábitat de especies.' },

  // ============ 05 | SISTEMAS COMPLEMENTARIOS [SC] ============
  { code: 'SC01', cat: 'SC', group: '', title: 'CHIMENEA SOLAR',
    text: 'Implementar este sistema para favorecer la extracción del aire caliente y viciado de los espacios, utilizando la diferencia de presión para succionarlo hacia arriba' },
  { code: 'SC02', cat: 'SC', group: '', title: 'GEOTERMIA',
    text: 'Implementar este sistema para reducir la demanda de climatización, utilizando la inercia térmica del suelo, que se mantiene a temperatura relativamente constante, para calentar/enfriar aire según la estación.' },

  // ============ 06 | ARTEFACTOS EFICIENTES [AE] ============
  { code: 'AE01', cat: 'AE', group: '', title: 'AGUA',
    text: 'Utilizar griferías con aireadores, inodoros de doble descarga, duchas de caudal limitado pudiendo disminuir un 58% el consumo de agua.' },
  { code: 'AE02', cat: 'AE', group: '', title: 'TECNOLOGÍA INVERTER',
    text: 'Priorizar la utilización de estos equipos para eliminar los picos de consumo eléctrico producidos durante los arranque del motor y mantener una estabilidad térmica constante. Reduciendo el consumo energético entre un 35-50%, aumentan el confort y la vida útil.',
    tabla: {
      headers: ['Cant.', 'Artefacto', 'Tiempo/Frecuencia', 'Consumo por unidad (L)', 'Día Entero (L)'],
      tradicionales: [
        ['Ducha', '6m (uso diario)', '10 L/min', '60'],
        ['Griferías baño', '3m / 5m', '7 L/min', '35'],
        ['Griferías cocina', '4m / 8m', '8 L/min', '64'],
        ['Inodoros', '3v / 5v', '8 L/descarga', '40'],
        ['Lavarropas', '0,4v / 0,4v', '100 L/carga', '100'],
      ],
      totalTradicionales: '299',
      eficientes: [
        ['Ducha', '6m (uso diario)', '6 L/min', '36'],
        ['Griferías baño', '3m / 5m', '3 L/min', '15'],
        ['Griferías cocina', '4m / 8m', '6 L/min', '48'],
        ['Inodoro (N°1)', '2v / 4v', '3 L/descarga', '12'],
        ['Inodoro (N°2)', '1v / 1v', '6 L/descarga', '6'],
        ['Lavarropas', '0,4v / 0,4v', '20 L/carga', '20'],
      ],
      totalEficientes: '137',
      caption: 'Tabla 1: Consumo de artefactos, tradicionales vs eficientes.\nFuente: Barreneche R. (2017). Elaboración: Propia',
    } },
  { code: 'AE03', cat: 'AE', group: '', title: 'AEROTERMIA',
    text: 'Aprovechar la energía térmica del exterior mediante una bomba de calor para proporcionar calefacción, refrigeración y agua caliente.',
    ventajas: ['Alta compacidad.', 'Mínima superficie de envolvente.', 'Por cada 1 kW de electricidad consumida, pueden generar 4 kW de energía térmica, es decir una eficiencia del 400%', 'Menor costo constructivo.', 'Circulaciones mínimas.'],
    desventajas: ['Inversión inicial elevada en comparación a los sistemas más utilizados de calefacción como los calefactores a gas o los aires acondicionados.', 'Unidad exterior voluminosa: Se debe contemplar un espacio exterior que permita el flujo del aire, teniendo en cuenta que el equipo emite ruidos y vibraciones.', 'Necesidad de una sala técnica de aproximadamente 2 a 4 m² con ventilación.'],
    ciclo: {
      intro: 'Funciona mediante un ciclo termodinámico de 4 pasos con un gas refrigerante:',
      pasos: [
        ['(1). Evaporación (Captación):', 'El aire exterior pasa por el evaporador. El refrigerante, que entra muy frío, roba calor del aire y se evapora (se convierte en gas).'],
        ['(2). Compresión (Consumo):', 'El compresor eléctrico aplasta ese gas. Al aumentar la presión, su temperatura se dispara. Aquí es donde "gastamos" electricidad.'],
        ['(3). Condensación (Cesión):', 'Ese gas caliente cede su calor al agua del circuito de calefacción de la casa. Al enfriarse, vuelve a estado líquido.'],
        ['(4). Expansión:', 'El líquido pasa por una válvula que libera la presión bruscamente, enfriándolo (como un spray desodorante al salir), quedando listo para volver a robar calor afuera.'],
      ] } },
  { code: 'AE04', cat: 'AE', group: '', title: 'CALDERA DE CONDENSACIÓN',
    text: 'Aprovechar la energía térmica del exterior incorporando una bomba de calor para proporcionar calefacción, refrigeración y agua caliente.',
    ventajas: ['Ahorro entre 25 y 35% de gas en comparación con un calefactor de tiro balanceado.'],
    desventajas: ['Se debe prever un sistema de desagüe: Puede generar entre 1 y 2 litros de agua por hora de funcionamiento.', 'Costo inicial más elevado que un sistema de calefacción de tiro balanceado, pero mucho más barato que el de la Geotermia y la Aerotermia.'],
    ciclo: {
      intro: 'Funciona mediante un ciclo termodinámico de 4 pasos con un gas refrigerante:',
      pasos: [
        ['(1). Mezcla y combustión:', 'El gas y el aire ingresan a la cámara para alimentar el quemador y generar la llama directa.'],
        ['(2). Ingreso del retorno frío:', 'El agua del circuito de calefacción regresa fría a la caldera por la tubería de Retorno de agua.'],
        ['(3). Recuperación de calor latente:', 'Al pasar por el serpentín secundario, el agua fría enfría los humos de la combustión. El vapor de agua que estos contienen se condensa, liberando energía térmica que precalienta el circuito.'],
        ['(4). Evacuación de condensados:', 'El agua líquida resultante del proceso de condensación se drena por la salida inferior de Condensación.'],
        ['(5). Calentamiento final e inyección:', 'El agua precalentada avanza hacia el intercambiador principal sobre la llama directa, alcanza la temperatura de diseño y sale impulsada a la red por la Inyección de agua.'],
        ['(6). Escape de humos limpios:', 'Los gases de combustión, ya despojados de la mayor parte de su calor y humedad, son expulsados a baja temperatura como Gas de condensación (humos residuales).'],
      ] } },

  // ============ 07 | ENERGÍAS RENOVABLES [ER] ============
  { code: 'ER01', cat: 'ER', group: 'Energía Fotovoltaica y solar', title: 'SISTEMAS ON GRID',
    text: 'Implementar sistema conectado a la red para que la vivienda consuma la energía que genere e inyecte los excedentes a la red pública, sin requerir baterías (menor costo y mantenimiento).' },
  { code: 'ER02', cat: 'ER', group: 'Energía Fotovoltaica y solar', title: 'SISTEMAS OFF GRID',
    text: 'Disponer sistema aislado de la red eléctrica para alcanzar autonomía energética, mediante un banco de baterías que implica un mayor costo y mantenimiento, recomendado para zonas rurales o donde no exista acceso a la red.' },
  { code: 'ER03', cat: 'ER', group: 'Energía Fotovoltaica y solar', title: 'TERMOTANQUE SOLAR',
    text: 'Aprovechar la energía solar para el calentamiento de agua de uso sanitario, calefacción y acondicionamiento térmico de piscinas.',
    tips: [
      'En la provincia de Santa Fe existe un programa llamado <b>“Prosumidores”</b> que permite generar energía renovable para auto consumo y vender la producción de energía excedente a la Empresa Provincial de la Energía (EPE). Además ofrecen reconocimientos económicos y créditos de inversión para la transición energética de energías renovables',
      'Los <b>paneles solares</b> buscan aprovechar la mayor cantidad de radiación durante todo el año. Se recomienda orientación norte, y una <b>inclinación de 32°</b> (próxima a la latitud local).',
      'Los <b>termotanques</b> buscan garantizar el suministro en la época desfavorable (invierno) y prevenir riesgos operativos por sobretemperatura en verano. Se recomienda orientación norte, y una <b>inclinación de 45°</b>.',
    ] },

  // ============ 08 | GESTIÓN DEL RECURSO HÍDRICO [RH] ============
  { code: 'RH01', cat: 'RH', group: '', title: 'REUTILIZACIÓN DE AGUAS GRISES',
    text: 'Reutilizar aguas de duchas, bañeras y lavamanos, posterior al tratamiento, para la descarga de inodoros, lavado y riego.' },
  { code: 'RH02', cat: 'RH', group: '', title: 'TRATAMIENTO DE AGUAS NEGRAS',
    text: 'Reutilizar aguas negras (inodoro), posterior a un tratamiento complejo, para uso de riego.' },
  { code: 'RH03', cat: 'RH', group: '', title: 'APROVECHAMIENTO DE AGUA DE LLUVIA',
    text: 'Almacenar agua de las cubiertas y utilizarla para lavar ropa, descargar inodoros, limpieza de pisos o regar.',
    tip: 'Reutilizando agua de lluvia, en una cubierta de 100 m2 podemos captar <b>90.000 litros de agua</b> anuales, ésto equivale a 41 descargas de inodoro diarias durante todo un año.' },
];

// Texto introductorio de la sección Vegetación (04 | P)
const VEGETACION_EXTRA = {
  intro: 'La incorporación estratégica de vegetación en el proyecto y su entorno inmediato aporta ventajas claves para el hábitat:',
  items: [
    ['Enfriamiento evaporativo:', 'Baja la temperatura del aire circundante por evapotranspiración, optimizando el microclima.'],
    ['Control lumínico:', 'Filtra la radiación solar directa y disminuye el deslumbramiento, mejorando el confort visual.'],
    ['Barrera acústica y ambiental:', 'Amortigua ruidos urbanos y colabora en la purificación del aire al retener material particulado.'],
    ['Privacidad visual:', 'Configura límites virtuales y protección de vistas sin obstruir las corrientes de ventilación natural.'],
    ['Confort psicológico:', 'Estimula el bienestar psicofísico de los usuarios a través de la integración biofílica con el paisaje.'],
  ],
  cierre: 'El uso prioritario de especies nativas actúa como un vector ecológico y cultural que preserva la biodiversidad local, restaura el paisaje original y demanda un menor mantenimiento hídrico en el territorio.',
  tip: 'Algunas <b>especies recomendadas</b> para viviendas en nuestra ecorregión son el Ñangapirí, Palo Jabón, Tala, Sangre de Drago, Espinillo, Jacarandá, Lapacho Amarillo y Curupi.',
};

// Intro de la sección 03 | Envolventes (consideraciones generales sobre color)
const ENVOLVENTES_COLOR = {
  p1: 'El <b>color</b> en las envolventes (techos, muros) tiene una influencia importante en el comportamiento térmico de una vivienda, ya que determina cuánta radiación solar absorben o reflejan las superficies.',
  oscuros: { label: 'Colores oscuros', sub: '(negro, gris oscuro, marrón oscuro)',
    items: ['Absorben una mayor proporción de la radiación solar.', 'Alcanzan temperaturas superficiales más elevadas.', 'Incrementan la transferencia de calor hacia el interior.', 'Pueden ser beneficiosos en climas fríos donde se busca aprovechar la ganancia solar.'] },
  claros: { label: 'Colores claros', sub: '(blanco, beige, gris claro)',
    items: ['Reflejan gran parte de la radiación solar.', 'Mantienen temperaturas superficiales más bajas.', 'Reducen las ganancias térmicas hacia el interior.', 'Son especialmente útiles en climas cálidos.'] },
  p2: 'Estudios han demostrado que las cubiertas claras pueden presentar temperaturas superficiales entre 20 y 30°C inferiores que cubiertas oscuras expuestas a las mismas condiciones de radiación solar.',
  p3: 'En la cubierta es donde el color tiene mayor impacto, porque reciben la mayor cantidad de radiación, aunque los muros también se ven altamente afectados. En ambos casos, para nuestra región es siempre recomendable utilizar colores claros.',
};

// Intro de la sección 08 | RH
const RH_INTRO = 'Según la subsecretaría de Ambiente y Desarrollo Sustentable de la nación, en Argentina, el consumo doméstico de agua es en promedio de 318 litros por habitante por día. Esto significa un 83% más que la media latinoamericana y 6,3 veces más que los estándares fijados por la OMS.\n\nLas siguientes estrategias contribuyen a disminuir considerablemente el consumo';


